# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

title: Camino
author: Marquis Kurt
description: A KISS theme for Jekyll

webmaster_email: contact@example.com

doc_img_url: "/images/cwp/"
cover_img_url: "/images/covers/"
profile_img_url: "/images/profile.jpg"

accent:
  light:
    standard: "rgb(255, 149, 0)"
    highlight: "#ffaa33"
  dark:
    standard: "rgb(255, 159, 10)"
    highlight: "#ffb23b"

navigation:
  - name: "Home"
    link: "/index.html"
  - name: "About"
    link: "/about.html"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'