# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

title: Camino
author: Marquis Kurt
description: A KISS theme for Jekyll

webmaster_email: webmaster@marquiskurt.net
copyright: "&copy; 2020 Marquis Kurt. Licensed unver MPL v2.0."

navigation:
  - name: "Home"
    link: "/index.html"
  - name: "Blog"
    link: "/blog.html"
  - name: "GitHub"
    link: "https://github.com/alicerunsonfedora/camino"
  - name: "YouTrack"
    link: "https://youtrack.marquiskurt.net/youtrack/issues/CMN"
  - name: "Example Post"
    link: "/2020/02/17/example_post.html"
  - name: "Example Article"
    link: "/example_article.html"

camino:
  doc_img_url: "/images/cwp/"
  cover_img_url: "/images/covers/"
  nav_profile:
    img_url: "logo.svg"
    flat: false
  theme:
    font: 'Inter'
    navbar: '#191919'
    body:
      light: '#ffffff'
      dark: '#212121'
    accent:
      light:
        standard: "rgb(255, 149, 0)"
        highlight: "#ffaa33"
      dark:
        standard: "rgb(255, 159, 10)"
        highlight: "#ffb23b"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins:
  - jekyll-octicons
  - jekyll-sitemap
  - jekyll-feed
  - kramdown